update tool and fix aks

diff --git a/setup/aks/nuvfile.yml b/setup/aks/nuvfile.yml
--- a/setup/aks/nuvfile.yml
+++ b/setup/aks/nuvfile.yml
@@ -26,22 +26,28 @@ vars:
   TMP: '{{if eq .D ""}}$NUV_TMP{{else}}\$NUV_TMP{{end}}'
 
 env:
-  KUBECONFIG: |-
-    if test -e $NUV_TMP/kubeconfig
-    then echo $NUV_TMP/kubeconfig
-    else echo ~/.kube/config
-    fi
+  KUBECONFIG:
+    sh: |-
+      if test -e $NUV_TMP/kubeconfig
+      then echo $NUV_TMP/kubeconfig
+      else echo ~/.kube/config
+      fi
 
 tasks:
 
+  update-yaml:
+    cmds:
+    - curl -L https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml >cert-manager.yaml
+    - curl -L "https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/aws/deploy.yaml" >ingress-deploy.yaml
+
   extract:
-    desc: extract kubeconfig to access
+    #desc: extract the kubeconfig to access
     silent: true
     cmds:
     - "{{.RUN}} az aks get-credentials --name $AKS_NAME --resource-group $AKS_NAME --overwrite-existing -f {{.TMP}}/kubeconfig"
 
   config:
-    desc: configure an AKS cluster
+    desc: configure an Azure AKS kubernetes cluster
     silent: true
     cmds:
     - nuv config aks
@@ -54,21 +60,56 @@ tasks:
 
   create:
     silent: true
-    desc: create aks cluster
+    desc: create an Azure AKS kubernetes cluster
     cmds:
     - task: prereq
     - "{{.DATA}} az account show --query 'id' -o tsv"
     - "{{.RUN}} az account set --subscription {{._DATA}}"
     - "{{.RUN}} az group create --name $AKS_NAME --location $AKS_REGION"
-    - "{{.RUN}} az aks create -g $AKS_NAME -n $AKS_NAME --enable-managed-identity --node-count $AKS_COUNT --node-osdisk-size=$AKS_DISK --node-vm-size=$AKS_VM --ssh-key-value=$AKS_SSHKEY"
+    - > 
+      {{.RUN}} az aks create 
+      -g $AKS_NAME -n $AKS_NAME 
+      --enable-managed-identity 
+      --node-count $AKS_COUNT 
+      --node-osdisk-size=$AKS_DISK 
+      --node-vm-size=$AKS_VM 
+      --ssh-key-value=$AKS_SSHKEY"
     - task: extract
+    - task: certman
+    - task: ingress
 
   delete:
     silent: true
-    desc: delete aks cluster
+    desc: delete the current Azure AKS cluster
     cmds:
     - echo "*** Deleting the $AKS_NAME cluster"
     - "{{.DATA}} az account show --query 'id' -o tsv"
     - "{{.RUN}} az account set --subscription {{._DATA}}"
     - "{{.RUN}} az aks delete --name $AKS_NAME --resource-group $AKS_NAME"
     - "{{.RUN}} rm {{.TMP}}/kubeconfig"
+
+  certman: 
+    cmds:
+      - |
+        if test -z "{{.DEL}}"
+        then {{.RUN}}  kubectl apply -f cert-manager.yaml
+        else kubectl apply -f cert-manager.yaml
+        fi
+
+  ingress:
+    cmds:
+      - |
+        if test -z "{{.DEL}}"
+        then {{.RUN}} retry -t 1000 -m 1800 kubectl apply -f ingress-deploy.yaml
+        else {{.RUN}} kubectl delete -f ingress-deploy.yaml
+        fi
+
+  lb:
+    silent: true
+    desc: show the load balancer
+    cmds:
+      - > 
+        kubectl -n ingress-nginx get svc/ingress-nginx-controller  
+        -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null
+        || die "load balancer not found"
+      - echo ""
