add email and simple password validation

diff --git a/admin/nuvfile.yml b/admin/nuvfile.yml
--- a/admin/nuvfile.yml
+++ b/admin/nuvfile.yml
@@ -17,7 +17,7 @@
 
 version: '3'
 vars:
-  DRY: true
+  DRY: false
 
 
 tasks:
@@ -31,8 +31,18 @@ tasks:
       export AUTH="$(nuv -random -u):$(nuv -random --str 64)"
       # check {{._username_}} is at least 5 chars long
       if [ ${#USERNAME} -lt 5 ]
-      then echo "User name must be at least 5 chars long: $USERNAME"
-           exit 1
+      then 
+        nuv -die "User name must be at least 5 chars long: $USERNAME"
+      fi
+      # check that {{.email}} is a valid email
+      if ! [[ "$EMAIL" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]
+      then 
+        nuv -die "Invalid email: $EMAIL"
+      fi
+      # check that password is not empty
+      if [ -z "$PASSWORD" ]
+      then 
+        nuv -die "Password cannot be empty"
       fi
       envsubst -i user-crd.yaml -o _user-crd.yaml
     - |
