feat: web upload with devel deploy

diff --git a/devel/nuvfile.yml b/devel/nuvfile.yml
--- a/devel/nuvfile.yml
+++ b/devel/nuvfile.yml
@@ -21,26 +21,35 @@ tasks:
   detect:
     silent: true
     desc: detect project in directory
+    env:
+      PACKAGES_PATH:
+        sh: |
+          P=$(realpath ./packages)
+          if [ ! -z {{._path_}} ]; then
+            P=$(realpath {{._path_}}/packages)
+          fi
+          echo $P
+      WEB_PATH:
+        sh: |
+          P=$(realpath ./web)
+          if [ ! -z {{._path_}} ]; then
+            P=$(realpath {{._path_}}/web)
+          fi
+          echo $P
+
     cmds:
       - |
-        export PACKAGES_PATH=$(realpath ./packages)
-        export WEB_PATH=$(realpath ./web)
-        if [ ! -z {{._path_}} ]; then
-          PACKAGES_PATH=$(realpath {{._path_}}/packages)
-          WEB_PATH=$(realpath {{._path_}}/web)
-        fi
-
         if [ -d "$PACKAGES_PATH" ] && [ -d "$WEB_PATH" ]; then
           echo "Packages and web directory present."  
           exit 0
         fi
 
-        if [ -d "$PACKAGES_PATH" ]; then
-          echo "Packages directory present."
-          exit 0
+        if [! -d "$PACKAGES_PATH" ]; then
+          echo "No project detected (missing packages directory)."
+          exit 1
         fi
-        if [ -d "$WEB_PATH" ]; then
-          echo "Web directory present."
+        if [! -d "$WEB_PATH" ]; then
+          echo "Project detected: packages directory found."
           exit 0
         fi
         die "No project detected (missing packages and web directory)."
@@ -50,7 +59,20 @@ tasks:
     desc: scan directory and generate nuvolaris manifest files
     cmds:
       - task: detect
-      - js scanner.js $SCAN_PATH
+      - |
+        if [ -f "$SCAN_PATH/packages/manifest.yaml" ]; then
+          if {{.__force}}
+          then 
+            rm $SCAN_PATH/packages/manifest.yaml
+            js scanner.js $SCAN_PATH
+            mv $NUV_TMP/manifest.yaml $SCAN_PATH/packages/manifest.yaml
+            echo "Manifest file overwritten in $SCAN_PATH/packages/manifest.yaml"
+          else
+            echo "Scan skipped: manifest file present (packages/manifest.yaml). Use --force to overwrite it.";
+          fi
+        else 
+          js scanner.js $SCAN_PATH
+        fi
     env:
       SCAN_PATH:
         sh: |
@@ -70,12 +92,10 @@ tasks:
           echo "Detected 'https://' prefix, cloning repository..."
           git clone {{._repo_or_path_}} $DEPLOY_PATH
         fi
-
-        echo "Scanning project..."
-        nuv devel scan $DEPLOY_PATH
-
-        echo "Deploying project..."
-        nuv project deploy $DEPLOY_PATH
+      - echo "Scanning project..."
+      - nuv devel scan $DEPLOY_PATH
+      - echo "Deploying project..."
+      - nuv project deploy $DEPLOY_PATH
     env:
       DEPLOY_PATH:
         sh: |
